version: "3.9"

services:

  db:
    image: postgres
    container_name: "todo-db"
    volumes:
      - d:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
    - "4222:5432"

volumes:
  d: